apiVersion: v1
kind: Service
metadata:
  name: {{ include "team-openslides.fullname" . }}-web
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8000
  selector:
    app: {{ include "team-openslides.fullname" . }}-web