kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: {{ include "team-openslides.fullname" . }}-web
  labels:
    app: {{ include "team-openslides.fullname" . }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "team-openslides.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "team-openslides.fullname" . }}-web
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      volumes:
       - name: os-data-vol
         persistentVolumeClaim:
           claimName: {{ include "team-openslides.fullname" . }}-data
      containers:
       - name: openslides
         image: jamct/openslides
         imagePullPolicy: {{ .Values.app.pullpolicy }}
         volumeMounts:
           - name: os-data-vol
             mountPath: "/root/.local/share/openslides"
         ports:
         - containerPort: 8000
         env:
          - name: TZ
            value: Europe/Paris
          - name: OPENSLIDES_SECRET
            value: {{ .Values.secrets.python }}